name: mytest_tfsec

on:
 workflow_dispatch :
 

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
       
      - name: Build an image from Dockerfile 1
        uses: triat/terraform-security-scan@v3
          
