name: mytest_tfsec

on:
 workflow_dispatch :
 

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repo
        uses: actions/checkout@master
       
      - name: Build an image from Dockerfile 1
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
